config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates_associated :list, :movie
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, format: { with: /\A.{6,}\z/ }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :restrict_with_error

  validates :title, :overview, :poster_url, :rating, presence: true
  validates :title, :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  # def destroy
  #   raise
  #   list_id = params[:id]
  #   @bookmark = Bookmark.where(movie_id: ,list_id: )
  # end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Cancel", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar-lewagon d-flex justify-content-between align-items-center px-5">
  <div class="my-2">
    <button class="btn btn-flat"->Your List</button>
  </div>
  <div class="my-2">
    <img class="avatar-large sharp-image" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
  </div>
  <div class="d-flex my-2">
    <%= link_to "Add new list", new_list_path, class: "btn btn-ghost" %>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url();">
  <div class="container">
    <h1>Your Lists</h1>
    <p>Cheeky</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>


<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Add new list", new_list_path %>

app/views/lists/new.html.erb
<h1>Add new List</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<%= link_to "Cancel", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul>
  <% @bookmarks.each do |bookmark|%>
    <li>
    <h3><%= bookmark.movie.title %></h3>
    <p><%= bookmark.movie.overview %></p>
    <img style="width: 100px" src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>">
    <p><%= bookmark.movie.rating.round(1) %></p>
    <p><%= bookmark.comment%></p>
    <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    </li>
  <% end %>
</ul>


<%= link_to "Add a bookmark", new_list_bookmark_path(@list) %>
<%= link_to "Back", lists_path %>